POSTGRES_HOST=postgres
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0password
POSTGRES_PORT=5432
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
WORKERS=2
CPU_TIME_LIMIT=5
WALL_TIME_LIMIT=10
MEMORY_LIMIT=262144
STACK_LIMIT=65536
MAX_PROCESSES_AND_OR_THREADS=60
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=false
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=false
MAX_FILE_SIZE=1024
AUTHN_HEADER=
AUTHN_TOKEN=
MAX_QUEUE_SIZE=100
MAINTENANCE_MODE=false
